### ISSUE TITLE
Add scientificNameID and namePublishedInID

### ISSUE THREAD

**Issue by rdmpage** [gbif/backbone-patch#1]
I suggest we add scientificNameID and namePublishedInID to the fields in the dataset. **scientificNameID** will help match the name with nomenclature data sets as and when they become available. For example, LSIDs for ION, IPNI, etc., UUIDs for Zoobank, and so on. This would also make it easier to locate names to be "retired" once they are available from "trusted checklists".

Adding **namePublishedInID** enables us to link directly to evidence (e.g., DOIs for relevant publication that published the name). I guess dcterms;references does this as well, although that is less specific than say "the name was published in this publication".

**Comment by mdoering** [comment]
Makes a lot of sense, Rod, yes. Ill add the column right away. GBIF does not handle those 2 terms elegantly so far, but we probably should in the near future so its good to keep track of those attributes.

**Comment by rdmpage** [comment]
Great, thanks!

**Comment by deepreef** [comment]
Guys -- this is GREAT progress!  I'm looking forward to diving into this as soon as I get back from Pohnpei.  One thing that would be very helpful to me:  What, exactly (and I mean EXACTLY) is the basis of record for this dataset? Does each row represent a unique text string (ala GNI)?  For example, would "Aus bus L." and "Aus bus Linnaeus" be considered duplicate records, or would they be intentionally mantained, but somehow cross-linked as representing the same "name"?  Or does it represent the same canonical name?  For example, "Aus bus L." and "Aus bus Linnaeus" would be considered duplicate records, but "Aus bus Linnaeus" and "Xus bus (Linnaeus)" would represent legitimately different records (different combinations of the same Protonym).  What about orthographic variants (e.g., "Aus bus Linnaeus" vs. "Aus buus Linnaeus") Duplicates? Or maintained as different? In order to cross-link to other identifiers (i.e., knowing whether the records are 1:1, 1:M, M:1, or M:M), we need to have a very clear and precise understanding of the basis of record.

**Comment by mdoering** [comment]
Rich, this is a taxonomic dataset which should treat taxa the way we like to see them in the GBIF backbone. So an entry can either be an accepted taxon or some kind of synonym which should point to its accepted name. We don't want to track different author abbreviations, but tracking orthographic variants could be done. We definitely want to track recombinations. 

But I don't expect this dataset to grow dramatically. It is not the comprehensive backbone itself. It should mostly be small patches to fix errors or override opinions in other sources (such as CoL, FauEuropaea, WoRMS but also IPNI) that we use to automatically build new GBIF backbone versions. Or list newly described names quickly which did not yet make it into other sources.
